# render.yaml - Frontend Deployment
services:
  - type: web
    name: vite-react-frontend
    env: static
    branch: main
    rootDir: /
    buildCommand: npm install && npm run build
    publishCommand: npm run build
    staticPublishPath: dist
    plan: free
